version: "3.9"
services:
    web:
      build: .

      volumes:
        - .:/app

      ports:
        - "80:80"

      image: teste_api_brasilprev:app

      container_name: container_api

      restart: always

      command: python3 manage.py runserver 0.0.0.0:80
      
                    
volumes:
  db_data: {}