# Generated by Django 4.1.5 on 2023-01-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('dataDeNascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('rendaMensal', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Cadastro Cliente',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('susep', models.CharField(max_length=200)),
                ('expiracaoDeVenda', models.DateField()),
                ('valorMinimoAporteInicial', models.FloatField()),
                ('valorMinimoAporteExtra', models.FloatField()),
                ('idadeDeEntrada', models.IntegerField()),
                ('idadeDeSaida', models.IntegerField()),
                ('carenciaInicialDeResgate', models.IntegerField()),
                ('carenciaEntreResgates', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cadastro Produto',
            },
        ),
        migrations.CreateModel(
            name='Contratacao_plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte', models.FloatField()),
                ('dataDaContratacao', models.DateField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastro_cliente')),
                ('idProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastro_produto')),
            ],
            options={
                'verbose_name_plural': 'Contratação Plano',
            },
        ),
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorResgate', models.FloatField()),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contratacao_plano')),
            ],
            options={
                'verbose_name_plural': 'Resgate',
            },
        ),
        migrations.CreateModel(
            name='Aporte_extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorAporte', models.FloatField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastro_cliente')),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contratacao_plano')),
            ],
            options={
                'verbose_name_plural': 'Aporte Extra',
            },
        ),
    ]
